version: "3.8"

services:
      
  database:
    container_name: database
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=metrics
    ports:
      - 27017:27017
